M48
; DRILL file {KiCad (7.0.0)} date Sun Mar 12 16:39:37 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-12T16:39:37+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0335
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.5423Y-4.7454
X4.7707Y-4.7454
T2
X5.0697Y-3.7046
X5.1878Y-3.7046
T3
X4.2303Y-3.5472
X6.5945Y-3.5472
T0
M30
