esphome:
  name: esphome-web-977c78
  friendly_name: EinkLichtSchalter
  on_boot: 
    - priority: 90
      then: 
      - output.turn_on: output_low

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "eUg44GR5HZ7II4hYVDfTM7lpok/CW376Z7KKFdylqnE="

ota:

time:
  - platform: homeassistant
    id: esptime

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-977C78"
    password: "2tkpr2Ni9vQW"

captive_portal:

sensor:
  - platform: homeassistant
    id: inside_co2
    entity_id: sensor.unknown_70_ee_50_27_ac_1e_co2
    internal: true

  - platform: homeassistant
    id: outside_temperature
    entity_id: sensor.unknown_70_ee_50_27_ac_1e_temperature
    internal: true

# Example configuration entry
font:
  - file: 'gfonts://Roboto'
    id: font1
    size: 8

spi:
  clk_pin: GPIO21
  mosi_pin: GPIO09

display:
  - platform: waveshare_epaper
    cs_pin: GPIO47
    dc_pin: GPIO38
    busy_pin: GPIO40
    reset_pin: GPIO39
    model: 2.70in
    reset_duration: 300ms
    update_interval: 360s
    rotation: 180
    #full_update_every: 30 
    id: epaper_display
    lambda: |-
      // Print "Mitt Smarta Hus" in top center.
      it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "Ulis Smart Haus");

      // Print time in HH:MM format
      it.strftime(0, 60, id(font1), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());

      // Print inside temperature (from homeassistant sensor)
      if (id(inside_co2).has_state()) {
        it.printf(127, 23, id(font1), TextAlign::TOP_RIGHT , "%.1f°", id(inside_co2).state);
      }

      // Print inside temperature (from homeassistant sensor)
      if (id(outside_temperature).has_state()) {
        it.printf(127, 60, id(font1), TextAlign::BASELINE_RIGHT , "%.1f°", id(outside_temperature).state);
      }

output:
- platform: gpio
  pin: GPIO12
  id: output_low 