M48
; DRILL file {KiCad (7.0.0)} date Mon Mar 27 21:22:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-27T21:22:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X4.501Y-3.1693
X4.7766Y-3.1693
X5.1396Y-2.5718
X5.1396Y-2.8474
T2
X5.3756Y-3.3599
T0
M30
