esphome:
  name: esphome-web-977c78
  friendly_name: EinkLichtSchalter
  on_boot: 
    - priority: 90
      then: 
      - output.turn_on: output_low

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "eUg44GR5HZ7II4hYVDfTM7lpok/CW376Z7KKFdylqnE="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-977C78"
    password: "2tkpr2Ni9vQW"

captive_portal:

# Example configuration entry
font:
  - file: 'gfonts://Roboto'
    id: font1
    size: 8

spi:
  clk_pin: GPIO21
  mosi_pin: GPIO09

display:
  - platform: waveshare_epaper
    cs_pin: GPIO47
    dc_pin: GPIO38
    busy_pin: GPIO40
    reset_pin: GPIO39
    model: 2.70in
    reset_duration: 300ms
    update_interval: 360s
    rotation: 180
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");

output:
- platform: gpio
  pin: GPIO12
  id: output_low 